/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package book;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Sofia
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jpass = new javax.swing.JPasswordField();
        jshowpass = new javax.swing.JCheckBox();
        jloginbutton = new javax.swing.JButton();
        jregisterbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 220, 100, 30);
        jPanel1.add(jemail);
        jemail.setBounds(480, 210, 190, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 270, 100, 30);
        jPanel1.add(jpass);
        jpass.setBounds(480, 260, 190, 40);

        jshowpass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jshowpass.setForeground(new java.awt.Color(255, 255, 255));
        jshowpass.setText("Show Password");
        jshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jshowpassActionPerformed(evt);
            }
        });
        jPanel1.add(jshowpass);
        jshowpass.setBounds(560, 300, 130, 30);

        jloginbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jloginbutton.setText("Login");
        jloginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jloginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(jloginbutton);
        jloginbutton.setBounds(580, 330, 100, 40);

        jregisterbutton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jregisterbutton.setText("Register");
        jregisterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregisterbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(jregisterbutton);
        jregisterbutton.setBounds(510, 400, 100, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I don't have an account");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 410, 160, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 850, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jshowpassActionPerformed
        // TODO add your handling code here:
        if (jshowpass.isSelected()){
            jpass.setEchoChar((char)0);
        }else{
            jpass.setEchoChar('*');

        }

    }//GEN-LAST:event_jshowpassActionPerformed

    private void jloginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jloginbuttonActionPerformed
        // TODO add your handling code here:

        String Email, Password, query, passDb = null;
        String SUrl,SUser,Spass;
            SUrl = "jdbc:mysql://localhost/java_user_database";
            SUser = "root";
            Spass = "";
            int notFound = 0;
            
        try{
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, Spass);
            Statement st = con.createStatement();
            
        if (jemail.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Please fill out First Name"); 
        }
        else if (jpass.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please fill out Password");    
        }else{ 
            Email = jemail.getText();
            Password = jpass.getText();
               
            query = "SELECT * FROM user WHERE email= '"+Email+"' ";
            ResultSet rs = st.executeQuery(query);
            while(rs.next()){
                passDb = rs.getString("password");
                notFound = 1;
            }
            
            if(notFound == 1 && Password.equals(passDb)){
                
                JOptionPane.showMessageDialog(null, "Log-in Successfully");
            
                Dashboard DashboardFrame = new Dashboard();
                DashboardFrame.setVisible(true);
                DashboardFrame.pack();
                DashboardFrame.setLocationRelativeTo(null);
                this.dispose();
            
            }else{
             JOptionPane.showMessageDialog(null, "Incorrect Email or Password");
            }
            jpass.setText("");             
        }
        }catch(HeadlessException | ClassNotFoundException | SQLException e){
            System.out.println("Error!" + e.getMessage());
        }    
    }//GEN-LAST:event_jloginbuttonActionPerformed

    private void jregisterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregisterbuttonActionPerformed
        // TODO add your handling code here:
        Register RegisterFrame = new Register();
        RegisterFrame.setVisible(true);
        RegisterFrame.pack();
        RegisterFrame.setLocationRelativeTo(null);
        this.dispose();

    }//GEN-LAST:event_jregisterbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jemail;
    private javax.swing.JButton jloginbutton;
    private javax.swing.JPasswordField jpass;
    private javax.swing.JButton jregisterbutton;
    private javax.swing.JCheckBox jshowpass;
    // End of variables declaration//GEN-END:variables
}
